version: '3'

services:
  postgresdb:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:${DB_PROXY_PORT}:5432"
    restart: unless-stopped
    volumes:
      - ./db-data/:/var/lib/postgresql/data

  relay-coston:
    container_name: ${COMPOSE_PROJECT_NAME}_server
    image: ${DOCKER_IMAGE_URL}
    command: start-relay --chain coston
    env_file:
      - .env
    depends_on:
      - postgresdb
    restart: unless-stopped
    volumes:
      - ./static/:/appdata/static
      - ./media/:/appdata/media

  relay-sepolia:
    container_name: ${COMPOSE_PROJECT_NAME}_server
    image: ${DOCKER_IMAGE_URL}
    command: start-relay --chain sepolia
    env_file:
      - .env
    depends_on:
      - postgresdb
    restart: unless-stopped
    volumes:
      - ./static/:/appdata/static
      - ./media/:/appdata/media
